### ISSUE TITLE
Hide Reorder Terms Query

### ISSUE THREAD

**Issue by eSaner** [ronalfy/reorder-by-term#5]
Feature Request:
The "Reorder Terms Query" message is confusing for clients.

![reorder-screenshot](https://cloud.githubusercontent.com/assets/6232891/15905818/5118485a-2d84-11e6-8af4-61044ed41fb5.jpg)

Can there be an option to hide/remove this? It could also just be wrapped in a div to be hidden via css.
Thanks!

**Comment by ronalfy** [comment]
I mostly use it to make it easier on the developers who use the plugin.

I'll add a show/hide button that when clicked, shows the code.

**Comment by eSaner** [comment]
It's certainly helpful to have it there! Just not necessary once everything
is working. Thanks for your time!

**Comment by ronalfy** [comment]
How about an option to disable it in the admin settings where the build
tools are?

I'm also curious of your use-case. This is the first feedback I've received.

**Comment by eSaner** [comment]
A checkbox there would work. Two other options that come to mind:

1. Is it possible to use Screen Options and have a checkbox to hide the
message like you can with metaboxes?
2. Combine the build tools with the Reorder Posts admin settings. Then have
two tabs in admin settings: Reorder Posts, and Reorder by Term, with build
tools and the remove message checkbox on the Reorder by Term tab.

On most sites I usually load a little css in the admin anyway, so really
just wrapping it all in a div would be fine. Then I'd just div{display:
none}.

I'm using the plugin on a site for a local (Virginia, USA) marketing and
brand management company. The site has a Services custom post type with a
Service Type custom taxonomy. On the frontend there's no Services index
page; the main pages for viewing Services are the Service Type archive
pages. These will be likely entrances and important pages SEO-wise, so they
wanted fine control over the order that services appear on the page. They
could have just adjusted the post date for each Service, but drag and drop
is much easier!

Thanks for the great plugin!

**Comment by ronalfy** [comment]
Great. Glad it's of use to you. I will consider all these options.

**Comment by ronalfy** [comment]
Sorry for the delay in implementing this.

Fixed with https://github.com/ronalfy/reorder-by-term/commit/410b328e2f5f74da6e0e814b63c84b22c4d88b6f

I'll be pushing to .org tonight. Just go to Settings->Reorder Posts and disable it.

**Comment by eSaner** [comment]
Works great. Thanks!
